<?php

namespace App\Actions\CKGSis\Customer\AjaxTransaction;

use Lorisleiva\Actions\Concerns\AsAction;

class TaxOfficesAction
{
    use AsAction;

    public function handle($request)
    {
        if ($request->plaque == null)
            return response()
                ->json(['status' => 0, 'message' => 'Plaka alanı zorunldur!'], 200);

        $plaka = $request->plaque;

        switch (strlen($plaka)) {
            case 1:
                $plaka = '00' . $plaka;
                break;

            case 2:
                $plaka = '0' . $plaka;
                break;

            case 3:
                $plaka = $plaka;
                break;
        }

        $json = collect(json_decode($this->jsonData()));

        $json = $json->toArray()[$plaka];

        return response()
            ->json(['status' => 1, 'data' => $json], 200);

    }

    public function jsonData()
    {
        return $json = '{
            "001":[
                {"code":"001251","tax_office":"5 OCAK VD"},
                {"code":"001114","tax_office":"ALADAĞ MAL MD."},
                {"code":"001201","tax_office":"CEYHAN VD"},
                {"code":"001255","tax_office":"ÇUKUROVA VD"},
                {"code":"001103","tax_office":"FEKE MAL MD."},
                {"code":"001115","tax_office":"İMAMOĞLU MAL MD."},
                {"code":"001205","tax_office":"KARATAŞ VD"},
                {"code":"001105","tax_office":"KARAİSALI MAL MD."},
                {"code":"001203","tax_office":"KOZAN VD"},
                {"code":"001109","tax_office":"POZANTI MAL MD."},
                {"code":"001110","tax_office":"SAİMBEYLİ MAL MD."},
                {"code":"001253","tax_office":"SEYHAN VD"},
                {"code":"001111","tax_office":"TUFANBEYLİ MAL MD."},
                {"code":"001112","tax_office":"YUMURTALIK MAL MD."},
                {"code":"001252","tax_office":"YÜREĞİR VD"},
                {"code":"001254","tax_office":"ZİYAPAŞA VD"}
            ],
            "002":[
                {"code":"002260","tax_office":"ADIYAMAN VD"},
                {"code":"002101","tax_office":"BESNİ MAL MD."},
                {"code":"002102","tax_office":"ÇELİKHAN MAL MD."},
                {"code":"002103","tax_office":"GERGER MAL MD."},
                {"code":"002104","tax_office":"GÖLBAŞI MAL MD."},
                {"code":"002261","tax_office":"KAHTA VD"},
                {"code":"002106","tax_office":"SAMSAT MAL MD."},
                {"code":"002107","tax_office":"SİNCİK MAL MD."},
                {"code":"002108","tax_office":"TUT MAL MD."}
            ],
            "003":[
                {"code":"003112","tax_office":"BAYAT MAL MD."},
                {"code":"003111","tax_office":"BAŞMAKÇI MAL MD."},
                {"code":"003261","tax_office":"BOLVADİN VD"},
                {"code":"003202","tax_office":"ÇAY VD"},
                {"code":"003114","tax_office":"ÇOBANLAR MAL MD."},
                {"code":"003103","tax_office":"DAZKIRI MAL MD."},
                {"code":"003260","tax_office":"DİNAR VD"},
                {"code":"003262","tax_office":"EMİRDAĞ VD"},
                {"code":"003115","tax_office":"EVCİLER MAL MD."},
                {"code":"003116","tax_office":"HOCALAR MAL MD."},
                {"code":"003105","tax_office":"İHSANİYE MAL MD."},
                {"code":"003113","tax_office":"İSCEHİSAR MAL MD."},
                {"code":"003117","tax_office":"KIZILÖREN MAL MD."},
                {"code":"003280","tax_office":"KOCATEPE VD"},
                {"code":"003263","tax_office":"SANDIKLI VD"},
                {"code":"003108","tax_office":"SULTANDAĞI MAL MD."},
                {"code":"003107","tax_office":"SİNANPAŞA MAL MD."},
                {"code":"003109","tax_office":"ŞUHUT MAL MD."},
                {"code":"003201","tax_office":"TINAZTEPE VD"}
                ],
                "068":[
                {"code":"068201","tax_office":"AKSARAY VD"},
                {"code":"068101","tax_office":"AĞAÇÖREN MAL MD."},
                {"code":"068105","tax_office":"ESKİL MAL MD."},
                {"code":"068106","tax_office":"GÜLAĞAÇ MAL MD."},
                {"code":"068102","tax_office":"GÜZELYURT MAL MD."},
                {"code":"068103","tax_office":"ORTAKÖY MAL MD."},
                {"code":"068104","tax_office":"SARIYAHŞİ MAL MD."}
                ],
                "005":[
                {"code":"005260","tax_office":"AMASYA VD"},
                {"code":"005262","tax_office":"G. HACIKÖY VD"},
                {"code":"005101","tax_office":"GÖYNÜCEK MAL MD."},
                {"code":"005102","tax_office":"GÜMÜŞHACIKÖY MAL MD."},
                {"code":"005106","tax_office":"HAMAMÖZÜ MAL MD."},
                {"code":"005261","tax_office":"MERZİFON VD"},
                {"code":"005264","tax_office":"SULUOVA VD"},
                {"code":"005263","tax_office":"TAŞOVA VD"}
                ],
                "006":[
                {"code":"006125","tax_office":"AKYURT MAL MD."},
                {"code":"006102","tax_office":"AYAŞ MAL MD."},
                {"code":"006103","tax_office":"BALA MAL MD."},
                {"code":"006276","tax_office":"BAŞKENT VD"},
                {"code":"006209","tax_office":"BEYPAZARI VD"},
                {"code":"006277","tax_office":"CUMHURİYET VD"},
                {"code":"006106","tax_office":"ÇAMLIDERE MAL MD."},
                {"code":"006257","tax_office":"ÇANKAYA VD"},
                {"code":"006211","tax_office":"ÇUBUK VD"},
                {"code":"006274","tax_office":"DIŞKAPI VD"},
                {"code":"006265","tax_office":"DOĞANBEY VD"},
                {"code":"006264","tax_office":"DİKİMEVİ VD"},
                {"code":"006215","tax_office":"ELMADAĞ VD"},
                {"code":"006275","tax_office":"ETİMESGUT VD"},
                {"code":"006127","tax_office":"EVREN MAL MD."},
                {"code":"006272","tax_office":"GÖLBAŞI VD"},
                {"code":"006110","tax_office":"GÜDÜL MAL MD."},
                {"code":"006213","tax_office":"HAYMANA VD"},
                {"code":"006268","tax_office":"HİTİT VD"},
                {"code":"006112","tax_office":"KALECİK MAL MD."},
                {"code":"006253","tax_office":"KAVAKLIDERE VD"},
                {"code":"006279","tax_office":"KAZAN VD"},
                {"code":"006124","tax_office":"KAZAN MAL MD."},
                {"code":"006278","tax_office":"KEÇİÖREN VD"},
                {"code":"006258","tax_office":"KIZILBEY VD"},
                {"code":"006115","tax_office":"KIZILCAHAMAM MAL MD."},
                {"code":"006270","tax_office":"M.KARAGÜZEL VD"},
                {"code":"006254","tax_office":"MALTEPE VD"},
                {"code":"006259","tax_office":"MİTHATPAŞA VD"},
                {"code":"006117","tax_office":"NALLIHAN MAL MD."},
                {"code":"006271","tax_office":"OSTİM VD"},
                {"code":"006205","tax_office":"POLATLI VD"},
                {"code":"006262","tax_office":"SEĞMENLER VD"},
                {"code":"006273","tax_office":"SİNCAN VD"},
                {"code":"006207","tax_office":"ŞEREFLİKOÇHİSAR VD"},
                {"code":"006260","tax_office":"ULUS VD"},
                {"code":"006263","tax_office":"ULUSİTE VD"},
                {"code":"006252","tax_office":"VERASET VE HARÇ VD"},
                {"code":"006269","tax_office":"Y.GALİP VD"},
                {"code":"006255","tax_office":"YENİMAHALLE VD"},
                {"code":"006266","tax_office":"YEĞENBEY VD"},
                {"code":"006261","tax_office":"YILDIRIMBEYAZIT VD"}
                ],
                "007":[
                {"code":"007101","tax_office":"AKSEKİ MAL MD."},
                {"code":"007201","tax_office":"ALANYA VD"},
                {"code":"007255","tax_office":"ANTALYA KURUMLAR VD"},
                {"code":"007112","tax_office":"DEMRE MAL MD."},
                {"code":"007254","tax_office":"DÜDEN VD"},
                {"code":"007204","tax_office":"ELMALI VD"},
                {"code":"007104","tax_office":"FİNİKE MAL MD."},
                {"code":"007105","tax_office":"GAZİPAŞA MAL MD."},
                {"code":"007106","tax_office":"GÜNDOĞMUŞ MAL MD."},
                {"code":"007113","tax_office":"İBRADI MAL MD."},
                {"code":"007252","tax_office":"KALEKAPI VD"},
                {"code":"007107","tax_office":"KAŞ MAL MD."},
                {"code":"007205","tax_office":"KEMER VD"},
                {"code":"007108","tax_office":"KORKUTELİ MAL MD."},
                {"code":"007206","tax_office":"KUMLUCA VD"},
                {"code":"007109","tax_office":"KUMLUCA MAL MD."},
                {"code":"007203","tax_office":"MANAVGAT VD"},
                {"code":"007253","tax_office":"MURATPAŞA VD"},
                {"code":"007202","tax_office":"SERİK VD"},
                {"code":"007251","tax_office":"ÜÇKAPILAR VD"}
                ],
                "075":[
                {"code":"075201","tax_office":"ARDAHAN VD"},
                {"code":"075101","tax_office":"ÇILDIR MAL MD."},
                {"code":"075102","tax_office":"DAMAL MAL MD."},
                {"code":"075103","tax_office":"GÖLE MAL MD."},
                {"code":"075104","tax_office":"HANAK MAL MD."},
                {"code":"075105","tax_office":"POSOF MAL MD."}
                ],
                "008":[
                {"code":"008101","tax_office":"ARDANUÇ MAL MD."},
                {"code":"008102","tax_office":"ARHAVİ MAL MD."},
                {"code":"008260","tax_office":"ARTVİN VD"},
                {"code":"008103","tax_office":"BORÇKA MAL MD."},
                {"code":"008261","tax_office":"HOPA VD"},
                {"code":"008107","tax_office":"MURGUL MAL MD."},
                {"code":"008105","tax_office":"ŞAVŞAT MAL MD."},
                {"code":"008106","tax_office":"YUSUFELİ MAL MD."}
                ],
                "009":[
                {"code":"009101","tax_office":"BOZDOĞAN MAL MD."},
                {"code":"009112","tax_office":"BUHARKENT MAL MD."},
                {"code":"009262","tax_office":"ÇİNE VD"},
                {"code":"009281","tax_office":"DİDİM VD"},
                {"code":"009201","tax_office":"EFELER VD"},
                {"code":"009263","tax_office":"GERMENCİK VD"},
                {"code":"009280","tax_office":"GÜZELHİSAR VD"},
                {"code":"009113","tax_office":"İNCİRLİOVA MAL MD."},
                {"code":"009104","tax_office":"KARACASU MAL MD."},
                {"code":"009114","tax_office":"KARPUZLU MAL MD."},
                {"code":"009105","tax_office":"KOÇARLI MAL MD."},
                {"code":"009115","tax_office":"KÖŞK MAL MD."},
                {"code":"009107","tax_office":"KUYUCAK MAL MD."},
                {"code":"009265","tax_office":"KUŞADASI VD"},
                {"code":"009260","tax_office":"NAZİLLİ VD"},
                {"code":"009110","tax_office":"SULTANHİSAR MAL MD."},
                {"code":"009261","tax_office":"SÖKE VD"},
                {"code":"009111","tax_office":"YENİPAZAR MAL MD."}
                ],
                "004":[
                {"code":"004260","tax_office":"AĞRI VD"},
                {"code":"004261","tax_office":"DOĞUBEYAZIT VD"},
                {"code":"004101","tax_office":"DİYADİN MAL MD."},
                {"code":"004103","tax_office":"ELEŞKİRT MAL MD."},
                {"code":"004104","tax_office":"HAMUR MAL MD."},
                {"code":"004105","tax_office":"PATNOS MAL MD."},
                {"code":"004106","tax_office":"TAŞLIÇAY MAL MD."},
                {"code":"004107","tax_office":"TUTAK MAL MD."}
                ],
                "010":[
                {"code":"010260","tax_office":"AYVALIK VD"},
                {"code":"010102","tax_office":"BALYA MAL MD."},
                {"code":"010261","tax_office":"BANDIRMA VD"},
                {"code":"010267","tax_office":"BİGADİÇ VD"},
                {"code":"010262","tax_office":"BURHANİYE VD"},
                {"code":"010269","tax_office":"DURSUNBEY VD"},
                {"code":"010263","tax_office":"EDREMİT VD"},
                {"code":"010266","tax_office":"ERDEK VD"},
                {"code":"010118","tax_office":"GÖMEÇ MAL MD."},
                {"code":"010264","tax_office":"GÖNEN VD"},
                {"code":"010110","tax_office":"HAVRAN MAL MD."},
                {"code":"010111","tax_office":"İVRİNDİ MAL MD."},
                {"code":"010201","tax_office":"KARESİ VD"},
                {"code":"010112","tax_office":"KEPSUT MAL MD."},
                {"code":"010280","tax_office":"KURTDERELİ VD"},
                {"code":"010113","tax_office":"MANYAS MAL MD."},
                {"code":"010117","tax_office":"MARMARA MAL MD."},
                {"code":"010114","tax_office":"SAVAŞTEPE MAL MD."},
                {"code":"010268","tax_office":"SINDIRGI VD"},
                {"code":"010265","tax_office":"SUSURLUK VD"}
                ],
                "074":[
                {"code":"074101","tax_office":"AMASRA MAL MD."},
                {"code":"074260","tax_office":"BARTIN VD"},
                {"code":"074102","tax_office":"KURUCAŞİLE MAL MD."},
                {"code":"074103","tax_office":"ULUS MAL MD."}
                ],
                "072":[
                {"code":"072260","tax_office":"BATMAN VD"},
                {"code":"072101","tax_office":"BEŞİRİ MAL MD."},
                {"code":"072102","tax_office":"GERCÜŞ MAL MD."},
                {"code":"072103","tax_office":"HASANKEYF MAL MD."},
                {"code":"072104","tax_office":"KOZLUK MAL MD."},
                {"code":"072105","tax_office":"SASON MAL MD."}
                ],
                "069":[
                {"code":"069101","tax_office":"AYDINTEPE MAL MD."},
                {"code":"069201","tax_office":"BAYBURT VD"},
                {"code":"069102","tax_office":"DEMİRÖZÜ MAL MD."}
                ],

                "014":[
                {"code":"014260","tax_office":"BOLU VD"},
                {"code":"014113","tax_office":"DÖRTDİVAN MAL MD."},
                {"code":"014262","tax_office":"GEREDE VD"},
                {"code":"014104","tax_office":"GÖYNÜK MAL MD."},
                {"code":"014105","tax_office":"KIBRISCIK MAL MD."},
                {"code":"014106","tax_office":"MENGEN MAL MD."},
                {"code":"014107","tax_office":"MUDURNU MAL MD."},
                {"code":"014108","tax_office":"SEBEN MAL MD."},
                {"code":"014114","tax_office":"YENİÇAĞA MAL MD."}
                ],
                "015":[
                {"code":"015101","tax_office":"AĞLASUN MAL MD."},
                {"code":"015108","tax_office":"ALTINYAYLA MAL MD."},
                {"code":"015261","tax_office":"BUCAK VD"},
                {"code":"015260","tax_office":"BURDUR VD"},
                {"code":"015109","tax_office":"ÇAVDIR MAL MD."},
                {"code":"015110","tax_office":"ÇELTİKÇİ MAL MD."},
                {"code":"015103","tax_office":"GÖLHİSAR MAL MD."},
                {"code":"015106","tax_office":"KARAMANLI MAL MD."},
                {"code":"015107","tax_office":"KEMER MAL MD."},
                {"code":"015104","tax_office":"TEFENNİ MAL MD."},
                {"code":"015105","tax_office":"YEŞİLOVA MAL MD."}
                ],
                "016":[
                {"code":"016112","tax_office":"BÜYÜKORHAN MAL MD."},
                {"code":"016253","tax_office":"ÇEKİRGE VD"},
                {"code":"016258","tax_office":"ERTUĞRULGAZİ VD"},
                {"code":"016201","tax_office":"GEMLİK VD"},
                {"code":"016259","tax_office":"GÖKDERE VD"},
                {"code":"016111","tax_office":"HARMANCIK MAL MD."},
                {"code":"016202","tax_office":"İNEGÖL VD"},
                {"code":"016207","tax_office":"İZNİK VD"},
                {"code":"016203","tax_office":"KARACABEY VD"},
                {"code":"016105","tax_office":"KELES MAL MD."},
                {"code":"016205","tax_office":"MUDANYA VD"},
                {"code":"016204","tax_office":"MUSTAFAKEMALPAŞA VD"},
                {"code":"016257","tax_office":"NİLÜFER VD"},
                {"code":"016108","tax_office":"ORHANELİ MAL MD."},
                {"code":"016206","tax_office":"ORHANGAZİ VD"},
                {"code":"016251","tax_office":"OSMANGAZİ VD"},
                {"code":"016254","tax_office":"SETBAŞI VD"},
                {"code":"016255","tax_office":"ULUDAĞ VD"},
                {"code":"016208","tax_office":"YENİŞEHİR VD"},
                {"code":"016256","tax_office":"YEŞİL VD"},
                {"code":"016252","tax_office":"YILDIRIM VD"}
                ],
                "011":[
                {"code":"011260","tax_office":"BİLECİK VD"},
                {"code":"011261","tax_office":"BOZÜYÜK VD"},
                {"code":"011102","tax_office":"GÖLPAZARI MAL MD."},
                {"code":"011107","tax_office":"İNHİSAR MAL MD."},
                {"code":"011103","tax_office":"OSMANELİ MAL MD."},
                {"code":"011104","tax_office":"PAZARYERİ MAL MD."},
                {"code":"011105","tax_office":"SÖĞÜT MAL MD."},
                {"code":"011106","tax_office":"YENİPAZAR MAL MD."}
                ],
                "012":[
                {"code":"012105","tax_office":"ADAKLI MAL MD."},
                {"code":"012260","tax_office":"BİNGÖL VD"},
                {"code":"012101","tax_office":"GENÇ MAL MD."},
                {"code":"012102","tax_office":"KARLIOVA MAL MD."},
                {"code":"012103","tax_office":"KIĞI MAL MD."},
                {"code":"012104","tax_office":"SOLHAN MAL MD."},
                {"code":"012106","tax_office":"YAYLADERE MAL MD."},
                {"code":"012107","tax_office":"YEDİSU MAL MD."}
                ],
                "013":[
                {"code":"013101","tax_office":"ADİLCEVAZ MAL MD."},
                {"code":"013102","tax_office":"AHLAT MAL MD."},
                {"code":"013260","tax_office":"BİTLİS VD"},
                {"code":"013106","tax_office":"GÜROYMAK MAL MD."},
                {"code":"013103","tax_office":"HİZAN MAL MD."},
                {"code":"013104","tax_office":"MUTKİ MAL MD."},
                {"code":"013261","tax_office":"TATVAN VD"}
                ],
                "020":[
                {"code":"020261","tax_office":"ACIPAYAM VD"},
                {"code":"020115","tax_office":"AKKÖY MAL MD."},
                {"code":"020111","tax_office":"BABADAĞ MAL MD."},
                {"code":"020116","tax_office":"BAKLAN MAL MD."},
                {"code":"020112","tax_office":"BEKİLLİ MAL MD."},
                {"code":"020117","tax_office":"BEYAĞAÇ MAL MD."},
                {"code":"020118","tax_office":"BOZKURT MAL MD."},
                {"code":"020263","tax_office":"BULDAN VD"},
                {"code":"020264","tax_office":"ÇAL VD"},
                {"code":"020104","tax_office":"ÇAMELİ MAL MD."},
                {"code":"020105","tax_office":"ÇARDAK MAL MD."},
                {"code":"020202","tax_office":"ÇINAR VD"},
                {"code":"020265","tax_office":"ÇİVRİL VD"},
                {"code":"020203","tax_office":"GÖKPINAR VD"},
                {"code":"020107","tax_office":"GÜNEY MAL MD."},
                {"code":"020113","tax_office":"HONAZ MAL MD."},
                {"code":"020108","tax_office":"KALE MAL MD."},
                {"code":"020280","tax_office":"PAMUKKALE VD"},
                {"code":"020260","tax_office":"SARAYKÖY VD"},
                {"code":"020201","tax_office":"SARAYLAR VD"},
                {"code":"020114","tax_office":"SERİNHİSAR MAL MD."},
                {"code":"020262","tax_office":"TAVAS VD"}
                ],
                "081":[
                {"code":"081261","tax_office":"AKÇAKOCA VD"},
                {"code":"081102","tax_office":"CUMAYERİ MAL MD."},
                {"code":"081103","tax_office":"ÇİLİMLİ MAL MD."},
                {"code":"081260","tax_office":"DÜZCE VD"},
                {"code":"081104","tax_office":"GÖLYAKA MAL MD."},
                {"code":"081105","tax_office":"GÜMÜŞOVA MAL MD."},
                {"code":"081106","tax_office":"KAYNAŞLI MAL MD."},
                {"code":"081107","tax_office":"YIĞILCA MAL MD."}
                ],
                "021":[
                {"code":"021101","tax_office":"BİSMİL MAL MD."},
                {"code":"021282","tax_office":"C. SITKI TARANCI VD"},
                {"code":"021102","tax_office":"ÇERMİK MAL MD."},
                {"code":"021103","tax_office":"ÇINAR MAL MD."},
                {"code":"021104","tax_office":"ÇÜNGÜŞ MAL MD."},
                {"code":"021105","tax_office":"DİCLE MAL MD."},
                {"code":"021112","tax_office":"EĞİL MAL MD."},
                {"code":"021106","tax_office":"ERGANİ MAL MD."},
                {"code":"021251","tax_office":"GÖKALP VD"},
                {"code":"021107","tax_office":"HANİ MAL MD."},
                {"code":"021108","tax_office":"HAZRO MAL MD."},
                {"code":"021113","tax_office":"KOCAKÖY MAL MD."},
                {"code":"021109","tax_office":"KULP MAL MD."},
                {"code":"021110","tax_office":"LİCE MAL MD."},
                {"code":"021111","tax_office":"SİLVAN MAL MD."},
                {"code":"021281","tax_office":"SÜLEYMANNAZİF VD"}
                ],
                "022":[
                {"code":"022201","tax_office":"ARDA VD"},
                {"code":"022101","tax_office":"ENEZ MAL MD."},
                {"code":"022263","tax_office":"HAVSA VD"},
                {"code":"022264","tax_office":"İPSALA VD"},
                {"code":"022261","tax_office":"KEŞAN VD"},
                {"code":"022260","tax_office":"KIRKPINAR VD"},
                {"code":"022105","tax_office":"LALAPAŞA MAL MD."},
                {"code":"022106","tax_office":"MERİÇ MAL MD."},
                {"code":"022108","tax_office":"SÜLOĞLU MAL MD."},
                {"code":"022262","tax_office":"UZUNKÖPRÜ VD"}
                ],
                "023":[
                {"code":"023101","tax_office":"AĞIN MAL MD."},
                {"code":"023110","tax_office":"ALACAKAYA MAL MD."},
                {"code":"023108","tax_office":"ARICAK MAL MD."},
                {"code":"023102","tax_office":"BASKİL MAL MD."},
                {"code":"023201","tax_office":"HARPUT VD"},
                {"code":"023280","tax_office":"HAZAR VD"},
                {"code":"023103","tax_office":"KARAKOÇAN MAL MD."},
                {"code":"023104","tax_office":"KEBAN MAL MD."},
                {"code":"023109","tax_office":"KOVANCILAR MAL MD."},
                {"code":"023105","tax_office":"MADEN MAL MD."},
                {"code":"023106","tax_office":"PALU MAL MD."},
                {"code":"023107","tax_office":"SİVRİCE MAL MD."}
                ],
                "025":[
                {"code":"025251","tax_office":"AZİZİYE VD"},
                {"code":"025101","tax_office":"AŞKALE MAL MD."},
                {"code":"025102","tax_office":"ÇAT MAL MD."},
                {"code":"025103","tax_office":"HINIS MAL MD."},
                {"code":"025104","tax_office":"HOROSAN MAL MD."},
                {"code":"025117","tax_office":"ILICA MAL MD."},
                {"code":"025105","tax_office":"İSPİR MAL MD."},
                {"code":"025114","tax_office":"KARAÇOBAN MAL MD."},
                {"code":"025106","tax_office":"KARAYAZI MAL MD."},
                {"code":"025280","tax_office":"KAZIMKARABEKİR VD"},
                {"code":"025118","tax_office":"KÖPRÜKÖY MAL MD."},
                {"code":"025107","tax_office":"NARMAN MAL MD."},
                {"code":"025108","tax_office":"OLTU MAL MD."},
                {"code":"025109","tax_office":"OLUR MAL MD."},
                {"code":"025110","tax_office":"PASİNLER MAL MD."},
                {"code":"025116","tax_office":"PAZARYOLU MAL MD."},
                {"code":"025111","tax_office":"ŞENKAYA MAL MD."},
                {"code":"025112","tax_office":"TEKMAN MAL MD."},
                {"code":"025113","tax_office":"TORTUM MAL MD."},
                {"code":"025115","tax_office":"UZUNDERE MAL MD."}
                ],
                "024":[
                {"code":"024101","tax_office":"ÇAYIRLI MAL MD."},
                {"code":"024260","tax_office":"FEVZİPAŞA VD"},
                {"code":"024102","tax_office":"İLİÇ MAL MD."},
                {"code":"024103","tax_office":"KEMAH MAL MD."},
                {"code":"024104","tax_office":"KEMALİYE MAL MD."},
                {"code":"024108","tax_office":"OTLUKBELİ MAL MD."},
                {"code":"024105","tax_office":"REFAHİYE MAL MD."},
                {"code":"024106","tax_office":"TERCAN MAL MD."},
                {"code":"024107","tax_office":"ÜZÜMLÜ MAL MD."}
                ],
                "026":[
                {"code":"026253","tax_office":"2 EYLÜL VD"},
                {"code":"026107","tax_office":"ALPU MAL MD."},
                {"code":"026254","tax_office":"BATTALGAZİ VD"},
                {"code":"026108","tax_office":"BEYLİKOVA MAL MD."},
                {"code":"026201","tax_office":"ÇİFTELER VD"},
                {"code":"026110","tax_office":"GÜNYÜZÜ MAL MD."},
                {"code":"026111","tax_office":"HAN MAL MD."},
                {"code":"026109","tax_office":"İNÖNÜ MAL MD."},
                {"code":"026102","tax_office":"MAHMUDİYE MAL MD."},
                {"code":"026112","tax_office":"MİHALGAZİ MAL MD."},
                {"code":"026103","tax_office":"MİHALIÇÇIK MAL MD."},
                {"code":"026104","tax_office":"SARICAKAYA MAL MD."},
                {"code":"026105","tax_office":"SEYİTGAZİ MAL MD."},
                {"code":"026202","tax_office":"SİVRİHİSAR VD"},
                {"code":"026106","tax_office":"SİVRİHİSAR MAL MD."},
                {"code":"026255","tax_office":"TAŞBAŞI VD"},
                {"code":"026252","tax_office":"YUNUSEMRE VD"}
                ],
                "027":[
                {"code":"027101","tax_office":"ARABAN MAL MD."},
                {"code":"027254","tax_office":"GAZİKENT VD"},
                {"code":"027203","tax_office":"İSLAHİYE VD"},
                {"code":"027107","tax_office":"KARKAMIŞ MAL MD."},
                {"code":"027255","tax_office":"KOZANLI VD"},
                {"code":"027202","tax_office":"NİZİP VD"},
                {"code":"027108","tax_office":"NURDAĞI MAL MD."},
                {"code":"027105","tax_office":"OĞUZELİ MAL MD."},
                {"code":"027251","tax_office":"SUBURCU VD"},
                {"code":"027253","tax_office":"ŞAHİNBEY VD"},
                {"code":"027252","tax_office":"ŞEHİTKAMİL VD"},
                {"code":"027106","tax_office":"YAVUZELİ MAL MD."}
                ],
                "029":[
                {"code":"029260","tax_office":"GÜMÜŞHANE VD"},
                {"code":"029102","tax_office":"KELKİT MAL MD."},
                {"code":"029107","tax_office":"KÖSE MAL MD."},
                {"code":"029108","tax_office":"KÜRTÜN MAL MD."},
                {"code":"029103","tax_office":"ŞİRAN MAL MD."},
                {"code":"029104","tax_office":"TORUL MAL MD."}
                ],
                "028":[
                {"code":"028101","tax_office":"ALUCRA MAL MD."},
                {"code":"028261","tax_office":"BULANCAK VD"},
                {"code":"028114","tax_office":"ÇAMOLUK MAL MD."},
                {"code":"028112","tax_office":"ÇANAKÇI MAL MD."},
                {"code":"028103","tax_office":"DERELİ MAL MD."},
                {"code":"028115","tax_office":"DOĞANKENT MAL MD."},
                {"code":"028104","tax_office":"ESPİYE MAL MD."},
                {"code":"028105","tax_office":"EYNESİL MAL MD."},
                {"code":"028260","tax_office":"GİRESUN VD"},
                {"code":"028106","tax_office":"GÖRELE MAL MD."},
                {"code":"028113","tax_office":"GÜCE MAL MD."},
                {"code":"028107","tax_office":"KEŞAP MAL MD."},
                {"code":"028110","tax_office":"PİRAZİZ MAL MD."},
                {"code":"028108","tax_office":"ŞEBİNKARAHİSAR MAL MD."},
                {"code":"028109","tax_office":"TİREBOLU MAL MD."},
                {"code":"028111","tax_office":"YAĞLIDERE MAL MD."}
                ],
                "030":[
                {"code":"030102","tax_office":"ÇUKURCA MAL MD."},
                {"code":"030260","tax_office":"HAKKARİ VD"},
                {"code":"030103","tax_office":"ŞEMDİNLİ MAL MD."},
                {"code":"030261","tax_office":"YÜKSEKOVA VD."}
                ],
                "031":[
                {"code":"031201","tax_office":"23 TEMMUZ VD"},
                {"code":"031281","tax_office":"AKDENİZ VD"},
                {"code":"031101","tax_office":"ALTINÖZÜ MAL MD."},
                {"code":"031203","tax_office":"ANTAKYA VD"},
                {"code":"031290","tax_office":"ASIM GÜNDÜZ VD"},
                {"code":"031110","tax_office":"BELEN MAL MD."},
                {"code":"031260","tax_office":"DÖRTYOL VD"},
                {"code":"031109","tax_office":"ERZİN MAL MD."},
                {"code":"031103","tax_office":"HASSA MAL MD."},
                {"code":"031261","tax_office":"KIRIKHAN VD"},
                {"code":"031111","tax_office":"KUMLU MAL MD."},
                {"code":"031262","tax_office":"REYHANLI VD"},
                {"code":"031202","tax_office":"SAHİL VD"},
                {"code":"031263","tax_office":"SAMANDAĞ VD"},
                {"code":"031280","tax_office":"ŞÜKRÜKANATLI VD"},
                {"code":"031108","tax_office":"YAYLADAĞ MAL MD."}
                ],
                "032":[
                {"code":"032110","tax_office":"AKSU MAL MD."},
                {"code":"032101","tax_office":"ATABEY MAL MD."},
                {"code":"032201","tax_office":"DAVRAZ VD"},
                {"code":"032261","tax_office":"EĞİRDİR VD"},
                {"code":"032103","tax_office":"GELENDOST MAL MD."},
                {"code":"032111","tax_office":"GÖNEN MAL MD."},
                {"code":"032260","tax_office":"KAYMAKKAPI VD"},
                {"code":"032104","tax_office":"KEÇİBORLU MAL MD."},
                {"code":"032105","tax_office":"SENİRKENT MAL MD."},
                {"code":"032106","tax_office":"SÜTÇÜLER MAL MD."},
                {"code":"032107","tax_office":"ŞARKİKARAAĞAÇ MAL MD."},
                {"code":"032108","tax_office":"ULUBORLU MAL MD."},
                {"code":"032262","tax_office":"YALVAÇ VD"},
                {"code":"032112","tax_office":"YENİŞARBADEMLİ M MAL MD."}
                ],
                "076":[
                {"code":"076101","tax_office":"ARALIK MAL MD."},
                {"code":"076201","tax_office":"IĞDIR VD"},
                {"code":"076102","tax_office":"KARAKOYUNLU MAL MD."},
                {"code":"076103","tax_office":"TUZLUCA MAL MD."}
                ],
                "046":[
                {"code":"046261","tax_office":"AFŞİN VD"},
                {"code":"046280","tax_office":"AKSU VD"},
                {"code":"046102","tax_office":"ANDIRIN MAL MD."},
                {"code":"046201","tax_office":"ASLANBEY VD"},
                {"code":"046107","tax_office":"ÇAĞLIYANCERİT MAL MD."},
                {"code":"046108","tax_office":"EKİNÖZÜ MAL MD."},
                {"code":"046260","tax_office":"ELBİSTAN VD"},
                {"code":"046104","tax_office":"GÖKSUN MAL MD."},
                {"code":"046109","tax_office":"NURHAK MAL MD."},
                {"code":"046262","tax_office":"PAZARCIK VD"},
                {"code":"046106","tax_office":"TÜRKOĞLU MAL MD."}
                ],
                "078":[
                {"code":"078101","tax_office":"EFLANİ MAL MD."},
                {"code":"078102","tax_office":"ESKİPAZAR MAL MD."},
                {"code":"078201","tax_office":"KARABÜK VD"},
                {"code":"078103","tax_office":"OVACIK MAL MD."},
                {"code":"078260","tax_office":"SAFRANBOLU VD"},
                {"code":"078105","tax_office":"YENİCE MAL MD."}
                ],
                "070":[
                {"code":"070101","tax_office":"AYRANCI MAL MD."},
                {"code":"070104","tax_office":"BAŞYAYLA MAL MD."},
                {"code":"070102","tax_office":"ERMENEK MAL MD."},
                {"code":"070103","tax_office":"K.KARABEKİR MAL MD."},
                {"code":"070201","tax_office":"KARAMAN VD"},
                {"code":"070105","tax_office":"SARIVELİLER MAL MD."}
                ],
                "036":[
                {"code":"036115","tax_office":"AKYAKA MAL MD."},
                {"code":"036103","tax_office":"ARPAÇAY MAL MD."},
                {"code":"036105","tax_office":"DİGOR MAL MD."},
                {"code":"036109","tax_office":"KAĞIZMAN MAL MD."},
                {"code":"036260","tax_office":"KARS VD"},
                {"code":"036111","tax_office":"SARIKAMIŞ MAL MD."},
                {"code":"036112","tax_office":"SELİM MAL MD."},
                {"code":"036113","tax_office":"SUSUZ MAL MD."}
                ],
                "037":[
                {"code":"037112","tax_office":"ABANA MAL MD."},
                {"code":"037116","tax_office":"AĞLI MAL MD."},
                {"code":"037101","tax_office":"ARAÇ MAL MD."},
                {"code":"037102","tax_office":"AZDAVAY MAL MD."},
                {"code":"037103","tax_office":"BOZKURT MAL MD."},
                {"code":"037104","tax_office":"CİDE MAL MD."},
                {"code":"037105","tax_office":"ÇATALZEYTİN MAL MD."},
                {"code":"037106","tax_office":"DADAY MAL MD."},
                {"code":"037107","tax_office":"DEVREKANİ MAL MD."},
                {"code":"037117","tax_office":"DOĞANYURT MAL MD."},
                {"code":"037118","tax_office":"HANÖNÜ MAL MD."},
                {"code":"037113","tax_office":"İHSANGAZİ MAL MD."},
                {"code":"037108","tax_office":"İNEBOLU MAL MD."},
                {"code":"037260","tax_office":"KASTAMONU VD"},
                {"code":"037109","tax_office":"KÜRE MAL MD."},
                {"code":"037114","tax_office":"PINARBAŞI MAL MD."},
                {"code":"037119","tax_office":"SEYDİLER MAL MD."},
                {"code":"037115","tax_office":"ŞENPAZAR MAL MD."},
                {"code":"037262","tax_office":"TAŞKÖPRÜ VD"},
                {"code":"037261","tax_office":"TOSYA VD"}
                ],
                "038":[
                {"code":"038111","tax_office":"AKKIŞLA MAL MD."},
                {"code":"038203","tax_office":"BÜNYAN VD"},
                {"code":"038201","tax_office":"DEVELİ VD"},
                {"code":"038252","tax_office":"ERCİYES VD"},
                {"code":"038103","tax_office":"FELAHİYE MAL MD."},
                {"code":"038254","tax_office":"GEVHER NESİBE VD"},
                {"code":"038113","tax_office":"HACILAR MAL MD."},
                {"code":"038104","tax_office":"İNCESU MAL MD."},
                {"code":"038253","tax_office":"KALEÖNÜ VD"},
                {"code":"038251","tax_office":"MİMARSİNAN VD"},
                {"code":"038114","tax_office":"ÖZVATAN MAL MD."},
                {"code":"038202","tax_office":"PINARBAŞI VD"},
                {"code":"038106","tax_office":"SARIOĞLAN MAL MD."},
                {"code":"038107","tax_office":"SARIZ MAL MD."},
                {"code":"038108","tax_office":"TOMARZA MAL MD."},
                {"code":"038109","tax_office":"YAHYALI MAL MD."},
                {"code":"038110","tax_office":"YEŞİLHİSAR MAL MD."}
                ],
                "071":[
                {"code":"071105","tax_office":"BALIŞEYH MAL MD."},
                {"code":"071106","tax_office":"ÇELEBİ MAL MD."},
                {"code":"071101","tax_office":"DELİCE MAL MD."},
                {"code":"071201","tax_office":"IRMAK VD"},
                {"code":"071202","tax_office":"KALETEPE VD"},
                {"code":"071107","tax_office":"KARAKEÇİLİ MAL MD."},
                {"code":"071102","tax_office":"KESKİN MAL MD."},
                {"code":"071103","tax_office":"SULAKYURT MAL MD."}
                ],
                "039":[
                {"code":"039262","tax_office":"BABAESKİ VD"},
                {"code":"039102","tax_office":"DEMİRKÖY MAL MD."},
                {"code":"039260","tax_office":"KIRKLARELİ VD"},
                {"code":"039103","tax_office":"KOFCAZ MAL MD."},
                {"code":"039261","tax_office":"LÜLEBURGAZ VD"},
                {"code":"039105","tax_office":"PEHLİVANKÖY MAL MD."},
                {"code":"039106","tax_office":"PINARHİSAR MAL MD."},
                {"code":"039107","tax_office":"VİZE MAL MD."}
                ],
                "040":[
                {"code":"040105","tax_office":"AKÇAKENT MAL MD."},
                {"code":"040104","tax_office":"AKPINAR MAL MD."},
                {"code":"040106","tax_office":"BOZTEPE MAL MD."},
                {"code":"040101","tax_office":"ÇİÇEKDAĞI MAL MD."},
                {"code":"040261","tax_office":"KAMAN VD"},
                {"code":"040260","tax_office":"KIRŞEHİR VD"},
                {"code":"040103","tax_office":"MUCUR MAL MD."}
                ],
                "041":[
                {"code":"041290","tax_office":"ACISU VD"},
                {"code":"041253","tax_office":"ALEMDAR VD"},
                {"code":"041207","tax_office":"DERİNCE VD"},
                {"code":"041204","tax_office":"GÖLCÜK VD"},
                {"code":"041203","tax_office":"İLYASBEY VD"},
                {"code":"041103","tax_office":"KANDIRA MAL MD."},
                {"code":"041205","tax_office":"KARAMÜRSEL VD"},
                {"code":"041206","tax_office":"KÖRFEZ VD"},
                {"code":"041252","tax_office":"TEPECİK VD"},
                {"code":"041202","tax_office":"ULUÇINAR VD"}
                ],
                "042":[
                {"code":"042124","tax_office":"AHIRLI MAL MD."},
                {"code":"042118","tax_office":"AKÖREN MAL MD."},
                {"code":"042201","tax_office":"AKŞEHİR VD"},
                {"code":"042254","tax_office":"ALAADDİN VD"},
                {"code":"042119","tax_office":"ALTINEKİN MAL MD."},
                {"code":"042204","tax_office":"BEYŞEHİR VD"},
                {"code":"042103","tax_office":"BOZKIR MAL MD."},
                {"code":"042205","tax_office":"CİHANBEYLİ VD"},
                {"code":"042125","tax_office":"ÇELTİK MAL MD."},
                {"code":"042206","tax_office":"ÇUMRA VD"},
                {"code":"042126","tax_office":"DERBENT MAL MD."},
                {"code":"042121","tax_office":"DEREBUCAK MAL MD."},
                {"code":"042106","tax_office":"DOĞANHİSAR MAL MD."},
                {"code":"042127","tax_office":"EMİRGAZİ MAL MD."},
                {"code":"042202","tax_office":"EREĞLİ VD"},
                {"code":"042128","tax_office":"GÜNEYSINIR MAL MD."},
                {"code":"042109","tax_office":"HADİM MAL MD."},
                {"code":"042129","tax_office":"HALKAPINAR MAL MD."},
                {"code":"042122","tax_office":"HÜYÜK MAL MD."},
                {"code":"042208","tax_office":"ILGIN VD"},
                {"code":"042111","tax_office":"KADINHAN MAL MD."},
                {"code":"042113","tax_office":"KARAPINAR MAL MD."},
                {"code":"042209","tax_office":"KULU VD"},
                {"code":"042253","tax_office":"MERAM VD"},
                {"code":"042252","tax_office":"MEVLANA VD"},
                {"code":"042115","tax_office":"SARAYÖNÜ MAL MD."},
                {"code":"042251","tax_office":"SELÇUK VD"},
                {"code":"042207","tax_office":"SEYDİŞEHİR VD"},
                {"code":"042123","tax_office":"TAŞKENT MAL MD."},
                {"code":"042130","tax_office":"TUZLUKCU MAL MD."},
                {"code":"042131","tax_office":"YALIHÜYÜK MAL MD."},
                {"code":"042117","tax_office":"YUNAK MAL MD."}
                ],
                "043":[
                {"code":"043201","tax_office":"30 AĞUSTOS VD"},
                {"code":"043101","tax_office":"ALTINTAŞ MAL MD."},
                {"code":"043107","tax_office":"ASLANAPA MAL MD."},
                {"code":"043111","tax_office":"ÇAVDARHİSAR MAL MD."},
                {"code":"043280","tax_office":"ÇİNİLİ VD"},
                {"code":"043102","tax_office":"DOMANİÇ MAL MD."},
                {"code":"043108","tax_office":"DUMLUPINAR MAL MD."},
                {"code":"043263","tax_office":"EMET VD"},
                {"code":"043260","tax_office":"GEDİZ VD"},
                {"code":"043109","tax_office":"HİSARCIK MAL MD."},
                {"code":"043112","tax_office":"PAZARLAR MAL MD."},
                {"code":"043261","tax_office":"SİMAV VD"},
                {"code":"043110","tax_office":"ŞAPHANE MAL MD."},
                {"code":"043262","tax_office":"TAVŞANLI VD"}
                ],
                "079":[
                {"code":"079201","tax_office":"KİLİS VD"}
                ],
                "044":[
                {"code":"044101","tax_office":"AKÇADAĞ MAL MD."},
                {"code":"044102","tax_office":"ARAPKİR MAL MD."},
                {"code":"044103","tax_office":"ARGUVAN MAL MD."},
                {"code":"044109","tax_office":"BATTALGAZİ MAL MD."},
                {"code":"044252","tax_office":"BEYDAĞI VD"},
                {"code":"044104","tax_office":"DARENDE MAL MD."},
                {"code":"044110","tax_office":"DOĞANYOL MAL MD."},
                {"code":"044105","tax_office":"DOĞANŞEHİR MAL MD."},
                {"code":"044251","tax_office":"FIRAT VD"},
                {"code":"044106","tax_office":"HEKİMHAN MAL MD."},
                {"code":"044111","tax_office":"KALE MAL MD."},
                {"code":"044112","tax_office":"KULUNCAK MAL MD."},
                {"code":"044107","tax_office":"PÖTÜRGE MAL MD."},
                {"code":"044113","tax_office":"YAZIHAN MAL MD."},
                {"code":"044108","tax_office":"YEŞİLYURT MAL MD."}
                ],
                "045":[
                {"code":"045113","tax_office":"AHMETLİ MAL MD."},
                {"code":"045201","tax_office":"AKHİSAR VD"},
                {"code":"045202","tax_office":"ALAŞEHİR VD"},
                {"code":"045251","tax_office":"ALAYBEY VD"},
                {"code":"045203","tax_office":"DEMİRCİ VD"},
                {"code":"045114","tax_office":"GÖLMARMARA MAL MD."},
                {"code":"045210","tax_office":"GÖRDES VD"},
                {"code":"045204","tax_office":"KIRKAĞAÇ VD"},
                {"code":"045115","tax_office":"KÖPRÜBAŞI MAL MD."},
                {"code":"045211","tax_office":"KULA VD"},
                {"code":"045252","tax_office":"MESİR VD"},
                {"code":"045205","tax_office":"SALİHLİ ADİL ORA VD"},
                {"code":"045206","tax_office":"SARIGÖL VD"},
                {"code":"045207","tax_office":"SARUHANLI VD"},
                {"code":"045110","tax_office":"SELENDİ MAL MD."},
                {"code":"045208","tax_office":"SOMA VD"},
                {"code":"045209","tax_office":"TURGUTLU VD"}
                ],
                "047":[
                {"code":"047112","tax_office":"DARGEÇİT MAL MD."},
                {"code":"047102","tax_office":"DERİK MAL MD."},
                {"code":"047261","tax_office":"KIZILTEPE VD"},
                {"code":"047260","tax_office":"MARDİN VD"},
                {"code":"047106","tax_office":"MAZIDAĞI MAL MD."},
                {"code":"047107","tax_office":"MİDYAT MAL MD."},
                {"code":"047262","tax_office":"NUSAYBİN VD"},
                {"code":"047109","tax_office":"ÖMERLİ MAL MD."},
                {"code":"047110","tax_office":"SAVUR MAL MD."},
                {"code":"047113","tax_office":"YEŞİLLİ MAL MD."}
                ],
                "033":[
                {"code":"033203","tax_office":"ANAMUR VD"},
                {"code":"033107","tax_office":"AYDINCIK MAL MD."},
                {"code":"033108","tax_office":"BOZYAZI MAL MD."},
                {"code":"033109","tax_office":"ÇAMLIYAYLA MAL MD."},
                {"code":"033201","tax_office":"ERDEMLİ VD"},
                {"code":"033103","tax_office":"GÜLNAR MAL MD."},
                {"code":"033250","tax_office":"İSTİKLAL VD"},
                {"code":"033204","tax_office":"KIZILMURAT VD"},
                {"code":"033254","tax_office":"LİMAN VD"},
                {"code":"033104","tax_office":"MUT MAL MD."},
                {"code":"033202","tax_office":"SİLİFKE VD"},
                {"code":"033205","tax_office":"ŞEHİTKERİM VD"},
                {"code":"033255","tax_office":"TOROS VD"},
                {"code":"033252","tax_office":"URAY VD"}
                ],
                "048":[
                {"code":"048261","tax_office":"BODRUM VD"},
                {"code":"048109","tax_office":"DALAMAN MAL MD."},
                {"code":"048102","tax_office":"DATÇA MAL MD."},
                {"code":"048262","tax_office":"FETHİYE VD"},
                {"code":"048111","tax_office":"KAVAKLIDERE MAL MD."},
                {"code":"048263","tax_office":"KÖYCEĞİZ VD"},
                {"code":"048265","tax_office":"MARMARİS VD"},
                {"code":"048264","tax_office":"MİLAS VD"},
                {"code":"048260","tax_office":"MUĞLA VD"},
                {"code":"048110","tax_office":"ORTACA MAL MD."},
                {"code":"048108","tax_office":"ULA MAL MD."},
                {"code":"048266","tax_office":"YATAĞAN VD"}
                ],
                "049":[
                {"code":"049101","tax_office":"BULANIK MAL MD."},
                {"code":"049104","tax_office":"HASKÖY MAL MD."},
                {"code":"049105","tax_office":"KORKUT MAL MD."},
                {"code":"049102","tax_office":"MALAZGİRT MAL MD."},
                {"code":"049260","tax_office":"MUŞ VD"},
                {"code":"049103","tax_office":"VARTO MAL MD."}
                ],
                "050":[
                {"code":"050107","tax_office":"ACIGÖL MAL MD."},
                {"code":"050101","tax_office":"AVANOS MAL MD."},
                {"code":"050102","tax_office":"DERİNKUYU MAL MD."},
                {"code":"050103","tax_office":"GÜLŞEHİR MAL MD."},
                {"code":"050104","tax_office":"HACIBEKTAŞ MAL MD."},
                {"code":"050105","tax_office":"KOZAKLI MAL MD."},
                {"code":"050260","tax_office":"NEVŞEHİR VD"},
                {"code":"050106","tax_office":"ÜRGÜP MAL MD."}
                ],
                "051":[
                {"code":"051106","tax_office":"ALTUNHİSAR MAL MD."},
                {"code":"051262","tax_office":"BOR VD"},
                {"code":"051103","tax_office":"ÇAMARDI MAL MD."},
                {"code":"051107","tax_office":"ÇİFTLİK MAL MD."},
                {"code":"051260","tax_office":"NİĞDE VD"},
                {"code":"051105","tax_office":"ULUKIŞLA MAL MD."}
                ],
                "052":[
                {"code":"052101","tax_office":"AKKUŞ MAL MD."},
                {"code":"052102","tax_office":"AYBASTI MAL MD."},
                {"code":"052201","tax_office":"BOZTEPE VD"},
                {"code":"052113","tax_office":"ÇAMAŞ MAL MD."},
                {"code":"052114","tax_office":"ÇATALPINAR MAL MD."},
                {"code":"052115","tax_office":"ÇAYBAŞI MAL MD."},
                {"code":"052261","tax_office":"FATSA VD"},
                {"code":"052104","tax_office":"GÖLKÖY MAL MD."},
                {"code":"052111","tax_office":"GÜLYALI MAL MD."},
                {"code":"052112","tax_office":"GÜRGENTEPE MAL MD."},
                {"code":"052116","tax_office":"İKİZCE MAL MD."},
                {"code":"052117","tax_office":"KABADÜZ MAL MD."},
                {"code":"052118","tax_office":"KABATAŞ MAL MD."},
                {"code":"052105","tax_office":"KORGAN MAL MD."},
                {"code":"052260","tax_office":"KÖPRÜBAŞI VD"},
                {"code":"052106","tax_office":"KUMRU MAL MD."},
                {"code":"052107","tax_office":"MESUDİYE MAL MD."},
                {"code":"052108","tax_office":"PERŞEMBE MAL MD."},
                {"code":"052109","tax_office":"ULUBEY MAL MD."},
                {"code":"052262","tax_office":"ÜNYE VD"}
                ],
                "080":[
                {"code":"080101","tax_office":"BAHÇE MAL MD."},
                {"code":"080102","tax_office":"DÜZİÇİ MAL MD."},
                {"code":"080104","tax_office":"HASANBEYLİ MAL MD."},
                {"code":"080260","tax_office":"KADİRLİ VD"},
                {"code":"080201","tax_office":"OSMANİYE VD"},
                {"code":"080105","tax_office":"SUMBAS MAL MD."},
                {"code":"080106","tax_office":"TOPRAKKALE MAL MD."}
                ],
                "053":[
                {"code":"053263","tax_office":"ARDEŞEN VD"},
                {"code":"053102","tax_office":"ÇAMLIHEMŞİN MAL MD."},
                {"code":"053261","tax_office":"ÇAYELİ VD"},
                {"code":"053109","tax_office":"DEREPAZARI MAL MD."},
                {"code":"053104","tax_office":"FINDIKLI MAL MD."},
                {"code":"053108","tax_office":"GÜNEYSU MAL MD."},
                {"code":"053110","tax_office":"HEMŞİN MAL MD."},
                {"code":"053105","tax_office":"İKİZDERE MAL MD."},
                {"code":"053111","tax_office":"İYİDERE MAL MD."},
                {"code":"053106","tax_office":"KALKANDERE MAL MD."},
                {"code":"053201","tax_office":"KAÇKAR VD"},
                {"code":"053262","tax_office":"PAZAR VD"},
                {"code":"053260","tax_office":"YEŞİLÇAY VD"}
                ],
                "054":[
                {"code":"054201","tax_office":"AKYAZI VD"},
                {"code":"054252","tax_office":"ALİ FUAT CEBESOY VD"},
                {"code":"054202","tax_office":"GEYVE VD"},
                {"code":"054251","tax_office":"GÜMRÜKÖNÜ VD"},
                {"code":"054203","tax_office":"HENDEK VD"},
                {"code":"054111","tax_office":"KARAPÜRÇEK MAL MD."},
                {"code":"054204","tax_office":"KARASU VD"},
                {"code":"054105","tax_office":"KAYNARCA MAL MD."},
                {"code":"054107","tax_office":"KOCAALİ MAL MD."},
                {"code":"054108","tax_office":"PAMUKOVA MAL MD."},
                {"code":"054106","tax_office":"SAPANCA MAL MD."},
                {"code":"054109","tax_office":"TARAKLI MAL MD."}
                ],
                "055":[
                {"code":"055251","tax_office":"19 MAYIS VD"},
                {"code":"055110","tax_office":"19 MAYIS MAL MD."},
                {"code":"055101","tax_office":"ALAÇAM MAL MD."},
                {"code":"055109","tax_office":"ASARCIK MAL MD."},
                {"code":"055113","tax_office":"AYVACIK MAL MD."},
                {"code":"055202","tax_office":"BAFRA VD"},
                {"code":"055203","tax_office":"ÇARŞAMBA VD"},
                {"code":"055252","tax_office":"GAZİLER VD"},
                {"code":"055205","tax_office":"HAVZA VD"},
                {"code":"055105","tax_office":"KAVAK MAL MD."},
                {"code":"055106","tax_office":"LADİK MAL MD."},
                {"code":"055111","tax_office":"SALIPAZARI MAL MD."},
                {"code":"055112","tax_office":"TEKKEKÖY MAL MD."},
                {"code":"055204","tax_office":"TERME VD"},
                {"code":"055108","tax_office":"VEZİRKÖPRÜ MAL MD."},
                {"code":"055114","tax_office":"YAKAKENT MAL MD."},
                {"code":"055290","tax_office":"ZAFER VD"}
                ],
                "057":[
                {"code":"057101","tax_office":"AYANCIK MAL MD."},
                {"code":"057261","tax_office":"BOYABAT VD"},
                {"code":"057103","tax_office":"DURAĞAN MAL MD."},
                {"code":"057107","tax_office":"DİKMEN MAL MD."},
                {"code":"057104","tax_office":"ERFELEK MAL MD."},
                {"code":"057105","tax_office":"GERZE MAL MD."},
                {"code":"057108","tax_office":"SARAYDÜZÜ MAL MD."},
                {"code":"057260","tax_office":"SİNOP VD"},
                {"code":"057106","tax_office":"TÜRKELİ MAL MD."}
                ],
                "058":[
                {"code":"058112","tax_office":"AKINCILAR MAL MD."},
                {"code":"058113","tax_office":"ALTINYAYLA MAL MD."},
                {"code":"058101","tax_office":"DİVRİĞİ MAL MD."},
                {"code":"058114","tax_office":"DOĞANŞAR MAL MD."},
                {"code":"058102","tax_office":"GEMEREK MAL MD."},
                {"code":"058115","tax_office":"GÖLOVA MAL MD."},
                {"code":"058103","tax_office":"GÜRÜN MAL MD."},
                {"code":"058104","tax_office":"HAFİK MAL MD."},
                {"code":"058105","tax_office":"İMRANLI MAL MD."},
                {"code":"058201","tax_office":"KALE VD"},
                {"code":"058106","tax_office":"KANGAL MAL MD."},
                {"code":"058107","tax_office":"KOYULHİSAR MAL MD."},
                {"code":"058280","tax_office":"SİTE VD"},
                {"code":"058109","tax_office":"SUŞEHRİ MAL MD."},
                {"code":"058260","tax_office":"ŞARKIŞLA VD"},
                {"code":"058116","tax_office":"ULAŞ MAL MD."},
                {"code":"058110","tax_office":"YILDIZELİ MAL MD."},
                {"code":"058111","tax_office":"ZARA MAL MD."}
                ],
                "056":[
                {"code":"056102","tax_office":"BAYKAN MAL MD."},
                {"code":"056104","tax_office":"ERUH MAL MD."},
                {"code":"056106","tax_office":"KURTALAN MAL MD."},
                {"code":"056107","tax_office":"PERVARİ MAL MD."},
                {"code":"056260","tax_office":"SİİRT VD"},
                {"code":"056110","tax_office":"ŞİRVAN MAL MD."}
                ],
                "059":[
                {"code":"059261","tax_office":"ÇERKEZKÖY VD"},
                {"code":"059262","tax_office":"ÇORLU VD"},
                {"code":"059263","tax_office":"HAYRABOLU VD"},
                {"code":"059264","tax_office":"MALKARA VD"},
                {"code":"059108","tax_office":"MARM. EREĞLİSİ MAL MD."},
                {"code":"059265","tax_office":"MURATLI VD"},
                {"code":"059260","tax_office":"NAMIK KEMAL VD"},
                {"code":"059106","tax_office":"SARAY MAL MD."},
                {"code":"059201","tax_office":"SÜLEYMANPAŞA VD"},
                {"code":"059107","tax_office":"ŞARKÖY MAL MD."}
                ],
                "060":[
                {"code":"060101","tax_office":"ALMUS MAL MD."},
                {"code":"060102","tax_office":"ARTOVA MAL MD."},
                {"code":"060110","tax_office":"BAŞÇİFTLİK MAL MD."},
                {"code":"060261","tax_office":"ERBAA VD"},
                {"code":"060262","tax_office":"NİKSAR VD"},
                {"code":"060108","tax_office":"PAZAR MAL MD."},
                {"code":"060105","tax_office":"REŞADİYE MAL MD."},
                {"code":"060111","tax_office":"SULUSARAY MAL MD."},
                {"code":"060260","tax_office":"TOKAT VD"},
                {"code":"060263","tax_office":"TURHAL VD"},
                {"code":"060109","tax_office":"YEŞİLYURT MAL MD."},
                {"code":"060264","tax_office":"ZİLE VD"}
                ],
                "061":[
                {"code":"061260","tax_office":"AKÇAABAT VD"},
                {"code":"061102","tax_office":"ARAKLI MAL MD."},
                {"code":"061103","tax_office":"ARSİN MAL MD."},
                {"code":"061111","tax_office":"BEŞİKDÜZÜ MAL MD."},
                {"code":"061113","tax_office":"ÇARŞIBAŞI MAL MD."},
                {"code":"061104","tax_office":"ÇAYKARA MAL MD."},
                {"code":"061114","tax_office":"DERNEKPAZARI MAL MD."},
                {"code":"061115","tax_office":"DÜZKÖY MAL MD."},
                {"code":"061116","tax_office":"HAYRAT MAL MD."},
                {"code":"061201","tax_office":"HIZIRBEY VD"},
                {"code":"061280","tax_office":"KARADENİZ VD"},
                {"code":"061117","tax_office":"KÖPRÜBAŞI MAL MD."},
                {"code":"061105","tax_office":"MAÇKA MAL MD."},
                {"code":"061261","tax_office":"OF VD"},
                {"code":"061107","tax_office":"SÜRMENE MAL MD."},
                {"code":"061112","tax_office":"ŞALPAZARI MAL MD."},
                {"code":"061108","tax_office":"TONYA MAL MD."},
                {"code":"061262","tax_office":"VAKFIKEBİR VD"},
                {"code":"061110","tax_office":"YOMRA MAL MD."}
                ],
                "062":[
                {"code":"062101","tax_office":"ÇEMİŞGEZEK MAL MD."},
                {"code":"062102","tax_office":"HOZAT MAL MD."},
                {"code":"062103","tax_office":"MAZGİRT MAL MD."},
                {"code":"062104","tax_office":"NAZİMİYE MAL MD."},
                {"code":"062105","tax_office":"OVACIK MAL MD."},
                {"code":"062106","tax_office":"PERTEK MAL MD."},
                {"code":"062107","tax_office":"PÜLÜMÜR MAL MD."},
                {"code":"062260","tax_office":"TUNCELİ VD"}
                ],
                "064":[
                {"code":"064261","tax_office":"BANAZ VD"},
                {"code":"064262","tax_office":"EŞME VD"},
                {"code":"064103","tax_office":"KARAHALLI MAL MD."},
                {"code":"064105","tax_office":"SİVASLI MAL MD."},
                {"code":"064104","tax_office":"ULUBEY MAL MD."},
                {"code":"064260","tax_office":"UŞAK VD"}
                ],
                "065":[
                {"code":"065108","tax_office":"BAHÇESARAY MAL MD."},
                {"code":"065101","tax_office":"BAŞKALE MAL MD."},
                {"code":"065109","tax_office":"ÇALDIRAN MAL MD."},
                {"code":"065102","tax_office":"ÇATAK MAL MD."},
                {"code":"065110","tax_office":"EDREMİT MAL MD."},
                {"code":"065201","tax_office":"ERCİŞ VD"},
                {"code":"065104","tax_office":"GEVAŞ MAL MD."},
                {"code":"065105","tax_office":"GÜRPINAR MAL MD."},
                {"code":"065106","tax_office":"MURADİYE MAL MD."},
                {"code":"065107","tax_office":"ÖZALP MAL MD."},
                {"code":"065111","tax_office":"SARAY MAL MD."},
                {"code":"065260","tax_office":"VAN VD"}
                ],
                "077":[
                {"code":"077101","tax_office":"ALTINOVA MAL MD."},
                {"code":"077102","tax_office":"ARMUTLU MAL MD."},
                {"code":"077103","tax_office":"ÇINARCIK MAL MD."},
                {"code":"077201","tax_office":"YALOVA VD"}
                ],
                "066":[
                {"code":"066101","tax_office":"AKDAĞMADENİ MAL MD."},
                {"code":"066109","tax_office":"AYDINCIK MAL MD."},
                {"code":"066261","tax_office":"BOĞAZLIYAN VD"},
                {"code":"066110","tax_office":"ÇANDIR MAL MD."},
                {"code":"066103","tax_office":"ÇAYIRALAN MAL MD."},
                {"code":"066104","tax_office":"ÇEKEREK MAL MD."},
                {"code":"066111","tax_office":"KADIŞEHRİ MAL MD."},
                {"code":"066112","tax_office":"SARAYKENT MAL MD."},
                {"code":"066105","tax_office":"SARIKAYA MAL MD."},
                {"code":"066262","tax_office":"SORGUN VD"},
                {"code":"066106","tax_office":"ŞEFAATLİ MAL MD."},
                {"code":"066113","tax_office":"YENİFAKILI MAL MD."},
                {"code":"066263","tax_office":"YERKÖY VD"},
                {"code":"066260","tax_office":"YOZGAT VD"}
                ],
                "067":[
                {"code":"067110","tax_office":"ALAPLI MAL MD."},
                {"code":"067263","tax_office":"ÇAYCUMA VD"},
                {"code":"067264","tax_office":"DEVREK VD"},
                {"code":"067113","tax_office":"GÖKÇEBEY MAL MD."},
                {"code":"067261","tax_office":"KARADENİZ EREĞLİ VD"},
                {"code":"067280","tax_office":"KARAELMAS VD"},
                {"code":"067201","tax_office":"UZUNMEHMET VD"}
                ],
                "017":[
                {"code":"017101","tax_office":"AYVACIK MAL MD."},
                {"code":"017102","tax_office":"BAYRAMİÇ MAL MD."},
                {"code":"017261","tax_office":"BİGA VD"},
                {"code":"017104","tax_office":"BOZCAADA MAL MD."},
                {"code":"017262","tax_office":"ÇAN VD"},
                {"code":"017260","tax_office":"ÇANAKKALE VD"},
                {"code":"017106","tax_office":"ECEABAT MAL MD."},
                {"code":"017107","tax_office":"EZİNE MAL MD."},
                {"code":"017263","tax_office":"GELİBOLU VD"},
                {"code":"017109","tax_office":"GÖKÇEADA MAL MD."},
                {"code":"017110","tax_office":"LAPSEKİ MAL MD."},
                {"code":"017111","tax_office":"YENİCE MAL MD."}
                ],
                "018":[
                {"code":"018110","tax_office":"ATKARACALAR MAL MD."},
                {"code":"018112","tax_office":"BAYRAMÖREN MAL MD."},
                {"code":"018260","tax_office":"ÇANKIRI VD"},
                {"code":"018101","tax_office":"ÇERKEŞ MAL MD."},
                {"code":"018102","tax_office":"ELDİVAN MAL MD."},
                {"code":"018104","tax_office":"ILGAZ MAL MD."},
                {"code":"018111","tax_office":"KIZILIRMAK MAL MD."},
                {"code":"018113","tax_office":"KORGUN MAL MD."},
                {"code":"018105","tax_office":"KURŞUNLU MAL MD."},
                {"code":"018106","tax_office":"ORTA MAL MD."},
                {"code":"018108","tax_office":"ŞABANÖZÜ MAL MD."},
                {"code":"018109","tax_office":"YAPRAKLI MAL MD."}
                ],
                "019":[
                {"code":"019101","tax_office":"ALACA MAL MD."},
                {"code":"019102","tax_office":"BAYAT MAL MD."},
                {"code":"019109","tax_office":"BOĞAZKALE MAL MD."},
                {"code":"019260","tax_office":"ÇORUM VD"},
                {"code":"019111","tax_office":"DODURGA MAL MD."},
                {"code":"019103","tax_office":"İSKİLİP MAL MD."},
                {"code":"019104","tax_office":"KARGI MAL MD."},
                {"code":"019113","tax_office":"LAÇİN MAL MD."},
                {"code":"019105","tax_office":"MECİTÖZÜ MAL MD."},
                {"code":"019112","tax_office":"OĞUZLAR MAL MD."},
                {"code":"019106","tax_office":"ORTAKÖY MAL MD."},
                {"code":"019107","tax_office":"OSMANCIK MAL MD."},
                {"code":"019261","tax_office":"SUNGURLU VD"},
                {"code":"019110","tax_office":"UĞURLUDAĞ MAL MD."}
                ],
                "034":[
                {"code":"034295","tax_office":"ADALAR VD"},
                {"code":"034244","tax_office":"ANADOLU KURUMLAR VD"},
                {"code":"034291","tax_office":"ATIŞALANI VD"},
                {"code":"034294","tax_office":"AVCILAR VD"},
                {"code":"034284","tax_office":"BAKIRKÖY VD"},
                {"code":"034264","tax_office":"BAYRAMPAŞA VD"},
                {"code":"034251","tax_office":"BEŞİKTAŞ VD"},
                {"code":"034265","tax_office":"BEYAZIT VD"},
                {"code":"034281","tax_office":"BEYKOZ VD"},
                {"code":"034297","tax_office":"BEYLİKDÜZÜ VD"},
                {"code":"034266","tax_office":"BEYOĞLU VD"},
                {"code":"034231","tax_office":"BOĞAZİÇİ KUR. VD"},
                {"code":"034230","tax_office":"BÜYÜK MÜK. VD. B VD"},
                {"code":"034204","tax_office":"BÜYÜKÇEKMECE VD"},
                {"code":"034250","tax_office":"ÇAPA VD"},
                {"code":"034206","tax_office":"ÇATALCA VD"},
                {"code":"034234","tax_office":"DAVUTPAŞA VD"},
                {"code":"034289","tax_office":"DIŞ TİC. VD"},
                {"code":"034255","tax_office":"ERENKÖY VD"},
                {"code":"034235","tax_office":"ESENLER VD"},
                {"code":"034236","tax_office":"FATİH VD"},
                {"code":"034268","tax_office":"GALATA VD"},
                {"code":"034269","tax_office":"GAZİOSMANPAŞA VD"},
                {"code":"034270","tax_office":"GÖZTEPE VD"},
                {"code":"034261","tax_office":"GÜNEŞLİ VD"},
                {"code":"034259","tax_office":"GÜNGÖREN VD"},
                {"code":"034278","tax_office":"HALKALI VD"},
                {"code":"034256","tax_office":"HİSAR VD"},
                {"code":"034271","tax_office":"HOCAPAŞA VD"},
                {"code":"034249","tax_office":"İKİTELLİ VD"},
                {"code":"034272","tax_office":"KADIKÖY VD"},
                {"code":"034279","tax_office":"KAĞITHANE VD"},
                {"code":"034285","tax_office":"KARTAL VD"},
                {"code":"034254","tax_office":"KASIMPAŞA VD"},
                {"code":"034273","tax_office":"KOCAMUSTAFAPAŞA VD"},
                {"code":"034260","tax_office":"KOCASİNAN VD"},
                {"code":"034246","tax_office":"KOZYATAĞI VD"},
                {"code":"034296","tax_office":"KÜÇÜKÇEKMECE VD"},
                {"code":"034237","tax_office":"KÜÇÜKKÖY VD"},
                {"code":"034262","tax_office":"KÜÇÜKYALI VD"},
                {"code":"034238","tax_office":"LALELİ VD"},
                {"code":"034232","tax_office":"MARMARA KUR. VD"},
                {"code":"034247","tax_office":"MASLAK VD"},
                {"code":"034274","tax_office":"MECİDİYEKÖY VD"},
                {"code":"034275","tax_office":"MERCAN VD"},
                {"code":"034239","tax_office":"MERTER VD"},
                {"code":"034240","tax_office":"MEVLANAKAPI VD"},
                {"code":"034287","tax_office":"NAKİL VASITA. VD"},
                {"code":"034267","tax_office":"NURUOSMANİYE VD"},
                {"code":"034263","tax_office":"PENDİK VD"},
                {"code":"034241","tax_office":"RAMİ VD"},
                {"code":"034258","tax_office":"RIHTIM VD"},
                {"code":"034288","tax_office":"SARIGAZİ VD"},
                {"code":"034283","tax_office":"SARIYER VD"},
                {"code":"034203","tax_office":"SİLİVRİ VD"},
                {"code":"034286","tax_office":"SULTANAHMET VD"},
                {"code":"034242","tax_office":"SULTANBEYLİ VD"},
                {"code":"034243","tax_office":"SÜLEYMANİYE VD"},
                {"code":"034205","tax_office":"ŞİLE VD"},
                {"code":"034276","tax_office":"ŞİŞLİ VD"},
                {"code":"034257","tax_office":"TUNA VD"},
                {"code":"034245","tax_office":"TUZLA VD"},
                {"code":"034233","tax_office":"ULAŞTIRMA VD"},
                {"code":"034252","tax_office":"ÜMRANİYE VD"},
                {"code":"034277","tax_office":"ÜSKÜDAR VD"},
                {"code":"034292","tax_office":"YAKACIK VD"},
                {"code":"034253","tax_office":"YEDİTEPE VD"},
                {"code":"034293","tax_office":"YENİ BOSNA VD"},
                {"code":"034280","tax_office":"ZEYTİNBURNU VD"},
                {"code":"034248","tax_office":"ZİNCİRLİKUYU VD"}
                ],
                "035":[
                {"code":"035251","tax_office":"9 EYLÜL VD"},
                {"code":"035213","tax_office":"ALİAĞA VD"},
                {"code":"035266","tax_office":"BALÇOVA VD"},
                {"code":"035255","tax_office":"BASMANE VD"},
                {"code":"035201","tax_office":"BAYINDIR VD"},
                {"code":"035254","tax_office":"BELKAHVE VD"},
                {"code":"035202","tax_office":"BERGAMA VD"},
                {"code":"035120","tax_office":"BEYDAĞ MAL MD."},
                {"code":"035264","tax_office":"BORNOVA VD"},
                {"code":"035265","tax_office":"ÇAKABEY VD"},
                {"code":"035212","tax_office":"ÇEŞME VD"},
                {"code":"035269","tax_office":"ÇİĞLİ VD"},
                {"code":"035105","tax_office":"DİKİLİ MAL MD."},
                {"code":"035268","tax_office":"EGE VD"},
                {"code":"035106","tax_office":"FOÇA MAL MD."},
                {"code":"035267","tax_office":"GAZİEMİR VD"},
                {"code":"035263","tax_office":"HASAN TAHSİN VD"},
                {"code":"035261","tax_office":"KADİFEKALE VD"},
                {"code":"035107","tax_office":"KARABURUN MAL MD."},
                {"code":"035256","tax_office":"KARŞIYAKA VD"},
                {"code":"035207","tax_office":"KEMALPAŞA VD"},
                {"code":"035257","tax_office":"KEMERALTI VD"},
                {"code":"035210","tax_office":"KINIK VD"},
                {"code":"035211","tax_office":"KİRAZ VD"},
                {"code":"035258","tax_office":"KONAK VD"},
                {"code":"035259","tax_office":"KORDON VD"},
                {"code":"035215","tax_office":"MENDERES VD"},
                {"code":"035203","tax_office":"MENEMEN VD"},
                {"code":"035204","tax_office":"ÖDEMİŞ VD"},
                {"code":"035114","tax_office":"SEFERİHİSAR MAL MD."},
                {"code":"035209","tax_office":"SELÇUK VD"},
                {"code":"035260","tax_office":"ŞİRİNYER VD"},
                {"code":"035262","tax_office":"TAŞITLAR VD"},
                {"code":"035205","tax_office":"TİRE VD"},
                {"code":"035206","tax_office":"TORBALI VD"},
                {"code":"035208","tax_office":"URLA VD"},
                {"code":"035252","tax_office":"YAMANLAR VD"}
                ],
                "063":[
                {"code":"063101","tax_office":"AKÇAKALE MAL MD."},
                {"code":"063262","tax_office":"BİRECİK VD"},
                {"code":"063103","tax_office":"BOZOVA MAL MD."},
                {"code":"063109","tax_office":"CEYLANPINAR MAL MD."},
                {"code":"063104","tax_office":"HALFETİ MAL MD."},
                {"code":"063110","tax_office":"HARRAN MAL MD."},
                {"code":"063105","tax_office":"HİLVAN MAL MD."},
                {"code":"063260","tax_office":"SİVEREK VD"},
                {"code":"063107","tax_office":"SURUÇ MAL MD."},
                {"code":"063201","tax_office":"ŞEHİTLİK VD"},
                {"code":"063280","tax_office":"TOPÇUMEYDANI VD"},
                {"code":"063261","tax_office":"VİRANŞEHİR VD"}
                ],
                "073":[
                {"code":"073101","tax_office":"BEYTÜŞŞEBAB MAL MD."},
                {"code":"073261","tax_office":"CİZRE VD"},
                {"code":"073102","tax_office":"CİZRE MAL MD."},
                {"code":"073103","tax_office":"GÜÇLÜKONAK MAL MD."},
                {"code":"073104","tax_office":"İDİL MAL MD."},
                {"code":"073262","tax_office":"SİLOPİ VD"},
                {"code":"073105","tax_office":"SİLOPİ MAL MD."},
                {"code":"073260","tax_office":"ŞIRNAK VD"},
                {"code":"073106","tax_office":"ULUDERE MAL MD."}
                ]
        }';
    }
}
